[package]
name = "rust-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = { version = "0.3.0", features = ["thread-pool"]}
tokio = { version = "1.17.0", features = ["full", ] }
tokio-util = { version = "0.7.0", features = ["full"] }
bytes = "1.0.0"
chrono = "0.4.19"
tracing = "0.1.29"
tracing-appender = "0.2.0"
tracing-subscriber = { version = "0.3.3" }
hello-world-derive = { path = "hello-world-derive" }

[[bin]]
name = "echo"
path = "src/echo.rs"

[[bin]]
name = "connect"
path = "src/connect.rs"

[[bin]]
name = "proxy"
path = "src/proxy.rs"

[[bin]]
name = "tcptest"
path = "src/tcptest.rs"

[[bin]]
name = "echo-udp"
path = "src/echo-udp.rs"

[[bin]]
name = "udpsplit"
path = "src/udpsplit.rs"

[[bin]]
name = "threadtest"
path = "src/threadtest.rs"

[[bin]]
name = "structest"
path = "src/structest.rs"

[[bin]]
name = "port-sniffer"
path = "src/port-sniffer.rs"

[[bin]]
name = "chat"
path = "src/chat.rs"

[[bin]]
name = "chat2_svr"
path = "src/chat2_svr.rs"

[[bin]]
name = "chat2_cli"
path = "src/chat2_cli.rs"

[[bin]]
name = "tokio-join"
path = "src/tokio-join.rs"

[[bin]]
name = "rt-test"
path = "src/rt-test.rs"

[[bin]]
name = "rt-test2"
path = "src/rt-test2.rs"

[[bin]]
name = "rt-join"
path = "src/rt-join.rs"

[[bin]]
name = "rt-task1"
path = "src/rt-task1.rs"

[[bin]]
name = "rt-task2"
path = "src/rt-task2.rs"

[[bin]]
name = "rt-task3"
path = "src/rt-task3.rs"

[[bin]]
name = "rt-task4"
path = "src/rt-task4.rs"

[[bin]]
name = "rt-select1"
path = "src/rt-select1.rs"

[[bin]]
name = "rt-select2"
path = "src/rt-select2.rs"

[[bin]]
name = "rt-timer1"
path = "src/rt-timer1.rs"

[[bin]]
name = "rt-timer2"
path = "src/rt-timer2.rs"

[[bin]]
name = "rt-timer3"
path = "src/rt-timer3.rs"

[[bin]]
name = "rt-timer4"
path = "src/rt-timer4.rs"

[[bin]]
name = "rt-timer5"
path = "src/rt-timer5.rs"

[[bin]]
name = "rt-timer6"
path = "src/rt-timer6.rs"

[[bin]]
name = "rt-timer7"
path = "src/rt-timer7.rs"

[[bin]]
name = "rt-sync01"
path = "src/rt-sync01.rs"

[[bin]]
name = "rt-sync02"
path = "src/rt-sync02.rs"

[[bin]]
name = "rt-sync03"
path = "src/rt-sync03.rs"

[[bin]]
name = "rt-sync04"
path = "src/rt-sync04.rs"

[[bin]]
name = "rt-sync05"
path = "src/rt-sync05.rs"

[[bin]]
name = "rt-sync06"
path = "src/rt-sync06.rs"

[[bin]]
name = "rt-sync07"
path = "src/rt-sync07.rs"

[[bin]]
name = "rt-sync08"
path = "src/rt-sync08.rs"

[[bin]]
name = "rt-sync09"
path = "src/rt-sync09.rs"

[[bin]]
name = "rt-sync10"
path = "src/rt-sync10.rs"

[[bin]]
name = "rt-sync11"
path = "src/rt-sync11.rs"

[[bin]]
name = "rt-sync12"
path = "src/rt-sync12.rs"

[[bin]]
name = "rt-sync13"
path = "src/rt-sync13.rs"

[[bin]]
name = "rt-sync14"
path = "src/rt-sync14.rs"

[[bin]]
name = "rt-sync15"
path = "src/rt-sync15.rs"

[[bin]]
name = "rt-sync16"
path = "src/rt-sync16.rs"

[[bin]]
name = "rt-sync17"
path = "src/rt-sync17.rs"

[[bin]]
name = "rt-sync18"
path = "src/rt-sync18.rs"

[[bin]]
name = "trace"
path = "src/trace.rs"

[[bin]]
name = "test01"
path = "bin/test01.rs"
