[package]
name = "rust-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = { version = "0.3.0", features = ["thread-pool"]}
tokio = { version = "1.17.0", features = ["full", ] }
tokio-util = { version = "0.7.0", features = ["full"] }
bytes = "1.0.0"
chrono = "0.4.19"
tracing = "0.1.29"
tracing-appender = "0.2.0"
tracing-subscriber = { version = "0.3.3" }
hello-world-derive = { path = "hello-world-derive" }
redis = { version = "0.22.1", features = ["tokio-comp"] }
structopt = { version = "0.3", default-features = false }
anyhow = "1.0.61"

[[bin]]
name = "test01"
path = "bin/test01.rs"

[[bin]]
name = "redis"
path = "bin/redis.rs"

[[bin]]
name = "asyncio"
path = "bin/asyncio.rs"
